### ISSUE TITLE
Pydub ffmpeg codec reliance

### ISSUE THREAD

**Issue by aadiltajani** [aadiltajani/CodeSten#2]
Pydub uses ffmpeg codec in background to do audio operations and need to be properly installed with path. Check if everyone can do it properly and need to mention steps and dependencies clearly

**Comment by Dhruvish-Patel** [comment]
It's working.

**Comment by asingh0404** [comment]
Yes it is working!

**Comment by ArpitCh21** [comment]
It's Working!

**Comment by aadiltajani** [comment]
Alright cool.
