### ISSUE TITLE
Audio file path issue on GitHub actions.

### ISSUE THREAD

**Issue by Dhruvish-Patel** [aadiltajani/CodeSten#6]
We are able to read the audio files in our local workspace but the same thing fails in the GitHub actions.

![image](https://user-images.githubusercontent.com/53443266/194427669-27a7b5fe-682e-4ba2-9ea1-58d56fa0160c.png)

![image](https://user-images.githubusercontent.com/53443266/194427956-03476766-9d05-41b0-a7d5-1fe376b96049.png)

**Comment by aadiltajani** [comment]
Issue with Data folder. Solved
