### ISSUE TITLE
Emotion analysis module fails

### ISSUE THREAD

**Issue by Dhruvish-Patel** [aadiltajani/CodeSten#7]
module 'emoji' has no attribute 'UNICODE_EMOJI'

![image](https://user-images.githubusercontent.com/53443266/194432824-a0366678-b0c4-437d-a537-0d1c9b46498f.png)

**Comment by aadiltajani** [comment]
[This error can be solved by downgrading underlying emoji module as referred here](https://github.com/aman2656/text2emotion-library/issues/10#issuecomment-1212279298)
